name: Playwright Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-integration:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers and system deps
        run: npx playwright install --with-deps
      - name: Build static assets
        run: npm run astro:build
      - name: Run Playwright tests
        run: npm run test:integration
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report-integration/
          retention-days: 3
